[ERROR] 2022-04-26 11:17:40.789 [main] ImportData - FATAL: database "MessCode" does not exist
org.postgresql.util.PSQLException: FATAL: database "MessCode" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2787) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:173) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:400) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:259) ~[postgresql-42.3.3.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at JDBC.ImportData.<init>(ImportData.java:33) [classes/:?]
	at com.messcode.server.networking.Server.start(Server.java:28) [classes/:?]
	at com.messcode.server.RunServer.main(RunServer.java:15) [classes/:?]
[ERROR] 2022-04-26 11:17:40.850 [main] ExportData - FATAL: database "MessCode" does not exist
org.postgresql.util.PSQLException: FATAL: database "MessCode" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2787) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:173) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:400) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:259) ~[postgresql-42.3.3.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at JDBC.ExportData.<init>(ExportData.java:32) [classes/:?]
	at com.messcode.server.networking.Server.start(Server.java:29) [classes/:?]
	at com.messcode.server.RunServer.main(RunServer.java:15) [classes/:?]
[ERROR] 2022-04-26 11:21:26.499 [Thread-0] ImportData - The column name account_id was not found in this ResultSet.
org.postgresql.util.PSQLException: The column name account_id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2901) ~[postgresql-42.3.3.jar:?]
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2779) ~[postgresql-42.3.3.jar:?]
	at JDBC.ImportData.updateLeader(ImportData.java:342) [classes/:?]
	at com.messcode.server.networking.ServerSocketHandler.run(ServerSocketHandler.java:76) [classes/:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
